import { Document, Page, Text, View } from "@react-pdf/renderer";
import type { TAssessmentConfig, TAssessmentResult } from "@formbricks/types/assessments";
import { PdfBarChart } from "./pdf-bar-chart";
import { PdfDimensionDetailsPage } from "./pdf-dimension-detail";
import { PdfHeader } from "./pdf-header";
import { PdfProfileSummary } from "./pdf-profile-summary";
import { PdfRadarChart } from "./pdf-radar-chart";
import { pdfStyles } from "./pdf-styles";

interface PdfDocumentProps {
  result: TAssessmentResult;
  config: TAssessmentConfig;
  respondentName?: string;
}

export const PdfDocument = ({ result, config, respondentName }: PdfDocumentProps): React.JSX.Element => {
  const { reportConfig, dimensions, interpretations } = config;
  const scores = result.normalizedScores;
  const footerText = reportConfig.footerText ?? "Generated by Formbricks";

  return (
    <Document
      title={reportConfig.title}
      author="Formbricks"
      subject="Assessment Report"
      creator="Formbricks Assessment Module"
    >
      {/* Page 1: Header + Profile Summary */}
      <Page size="A4" style={pdfStyles.page}>
        <PdfHeader
          reportConfig={reportConfig}
          respondentName={respondentName}
          date={result.createdAt}
        />
        <PdfProfileSummary profile={result.profile} />

        {/* AI Insights if available */}
        {result.aiInsights ? (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>AI Insights</Text>
            <Text style={pdfStyles.text}>{result.aiInsights}</Text>
          </View>
        ) : null}

        <Text style={pdfStyles.footer} fixed>
          {footerText}
        </Text>
      </Page>

      {/* Page 2: Charts */}
      <Page size="A4" style={pdfStyles.page}>
        <Text style={pdfStyles.sectionTitle}>Score Overview</Text>

        {reportConfig.showRadarChart ? (
          <View style={pdfStyles.section}>
            <Text style={[pdfStyles.textBold, { marginBottom: 8 }]}>Radar Chart</Text>
            <PdfRadarChart scores={scores} dimensions={dimensions} />
          </View>
        ) : null}

        {reportConfig.showBarChart ? (
          <View style={pdfStyles.section}>
            <Text style={[pdfStyles.textBold, { marginBottom: 8 }]}>Score Breakdown</Text>
            <PdfBarChart scores={scores} dimensions={dimensions} />
          </View>
        ) : null}

        <Text style={pdfStyles.footer} fixed>
          {footerText}
        </Text>
      </Page>

      {/* Page 3+: Dimension Details */}
      {reportConfig.showDimensionDetails ? (
        <Page size="A4" style={pdfStyles.page} wrap>
          <PdfDimensionDetailsPage
            dimensions={dimensions}
            scores={scores}
            interpretations={interpretations}
          />
          <Text style={pdfStyles.footer} fixed>
            {footerText}
          </Text>
        </Page>
      ) : null}
    </Document>
  );
};
